In [3]:
import pandas as pd

In [4]:
realestate_df = pd.read_csv('world_real_estate_data.csv')

# Cleaning Second Based on First Column

# To handel missing column under "country" we are using whatever after the comma under title to extract the missing field.

In [5]:
missing_country = realestate_df['country'].isna() #finds all the empty rows under country 
realestate_df.loc [missing_country, 'country'] = realestate_df.loc [missing_country, 'title'].str.split (',').str[-1].str.strip() #extacting the country from the title, the last word after the country 
realestate_df

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
0,2 room apartment 120 m² in Mediterranean Regio...,Turkey,"Mediterranean Region, Turkey",NaN,5.0,1.0,3.0,2.0,2.0,120 m²,110 m²,315209.0,https://realting.com/uploads/bigSlider/ab3/888...,https://realting.com/property-for-sale/turkey/...
1,"4 room villa 500 m² in Kalkan, Turkey",Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,NaN,NaN,NaN,500 m²,480 m²,1108667.0,https://realting.com/uploads/bigSlider/87b/679...,https://realting.com/property-for-sale/turkey/...
2,"1 room apartment 65 m² in Antalya, Turkey",Turkey,"Mediterranean Region, Antalya, Turkey",NaN,5.0,2.0,2.0,1.0,1.0,65 m²,60 m²,173211.0,https://realting.com/uploads/bigSlider/030/a11...,https://realting.com/property-for-sale/turkey/...
3,"1 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2020.0,15.0,5.0,2.0,1.0,1.0,NaN,40 m²,99900.0,https://realting.com/uploads/bigSlider/e9a/e06...,https://realting.com/property-for-sale/thailan...
4,"2 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2026.0,8.0,3.0,3.0,2.0,1.0,NaN,36 m²,67000.0,https://realting.com/uploads/bigSlider/453/aa2...,https://realting.com/property-for-sale/thailan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147531,"5 room apartment 310 m² in Gazipasa, Turkey",Turkey,"Mediterranean Region, Gazipasa, Turkey",NaN,NaN,NaN,NaN,5.0,NaN,310 m²,NaN,597810.0,https://realting.com/uploads/bigSlider/e4a/67f...,https://realting.com/property-for-sale/turkey/...
147532,"4 room apartment 192 m² in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",2023.0,5.0,NaN,5.0,4.0,2.0,192 m²,151 m²,637195.0,https://realting.com/uploads/bigSlider/93e/5c6...,https://realting.com/property-for-sale/turkey/...
147533,"2 room apartment in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",NaN,NaN,NaN,3.0,2.0,2.0,NaN,84 m²,477146.0,https://realting.com/uploads/bigSlider/4ae/9d8...,https://realting.com/property-for-sale/turkey/...
147534,"Apartment in Akarca, Turkey",Turkey,"Akarca, Central Anatolia Region, Turkey",2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,819163.0,https://realting.com/uploads/bigSlider/164/7e6...,https://realting.com/property-for-sale/turkey/...
147535,"4 room apartment 140 m² in, Turkey",Turkey,Turkey,NaN,2.0,NaN,5.0,4.0,NaN,140 m²,NaN,939164.0,https://realting.com/uploads/bigSlider/fab/0eb...,https://realting.com/property-for-sale/turkey/...

In [6]:
realestate_df.sample (10) #running randoms to test

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
76884,"1 room apartment 46 m² in Mahilyow, Belarus",Belarus,"Mahilyow Region, Mahilyow, Belarus",2023.0,10.0,8.0,1.0,NaN,1.0,46 m²,18 m²,32317.0,https://realting.com/uploads/bigSlider/bc4/c4b...,https://realting.com/property-for-sale/belarus...
70565,"Apartment 68 m² in Saint Petersburg, Russia",Russia,"Northwestern Federal District, Saint Petersbur...",NaN,NaN,NaN,NaN,NaN,NaN,68 m²,43 m²,288200.0,https://realting.com/uploads/bigSlider/423/030...,https://realting.com/property-for-sale/russia/...
28083,"2 room apartment 95 m² in Ciplakli, Turkey",Turkey,"Ciplakli, Mediterranean Region, Alanya, Turkey",2025.0,6.0,NaN,3.0,2.0,2.0,95 m²,86 m²,303253.0,https://realting.com/uploads/bigSlider/5ac/626...,https://realting.com/property-for-sale/turkey/...
67325,"2 room apartment 46 m² in Vsevolozhsk, Russia",Russia,"Northwestern Federal District, Vsevolozhsk, Vs...",2025.0,12.0,8.0,2.0,NaN,1.0,46 m²,NaN,70651.0,https://realting.com/uploads/bigSlider/3f6/01a...,https://realting.com/property-for-sale/russia/...
18535,"2 room apartment 50 m² in Kargicak, Turkey",Turkey,"Kargicak, Mediterranean Region, Alanya, Turkey",NaN,5.0,1.0,2.0,NaN,NaN,50 m²,NaN,224072.0,https://realting.com/uploads/bigSlider/d7b/c94...,https://realting.com/property-for-sale/turkey/...
108605,"3 room house 116 m² in Costa Blanca, Spain",Spain,"Valencian Community, Costa Blanca, Spain",NaN,NaN,NaN,NaN,NaN,NaN,116 m²,NaN,288952.0,https://realting.com/uploads/bigSlider/f84/628...,https://realting.com/property-for-sale/spain/e...
24884,"3 room apartment 155 m² in Bueyuekkumla, Turkey",Turkey,"Bueyuekkumla, Marmara Region, Gemlik, Turkey",2023.0,4.0,1.0,4.0,3.0,2.0,155 m²,130 m²,164126.0,https://realting.com/uploads/bigSlider/754/3db...,https://realting.com/property-for-sale/turkey/...
146066,"1 room apartment 43 m² in Prague, Czech Republic",Czech Republic,"Prague, Czech Republic",NaN,NaN,NaN,2.0,1.0,NaN,43 m²,NaN,305453.0,https://realting.com/uploads/bigSlider/e18/c31...,https://realting.com/property-for-sale/czech-r...
139889,"3 room house 240 m² in Smiltene, Latvia",Latvia,"Smiltene, Vidzeme, Smiltenes novads, Latvia",2008.0,NaN,NaN,NaN,NaN,NaN,240 m²,NaN,278704.0,https://realting.com/uploads/bigSlider/7b0/57a...,https://realting.com/property-for-sale/latvia/...
111242,"House 70 m² in Montenegro, Montenegro",Montenegro,Montenegro,NaN,NaN,NaN,NaN,NaN,NaN,70 m²,NaN,43477.0,https://realting.com/uploads/bigSlider/676/6ed...,https://realting.com/property-for-sale/montene...

In [7]:
realestate_df.sample(3)

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
65771,"1 room apartment 26 m² in Sochi, Russia",Russia,"South Federal District, Sochi, Resort Town of ...",NaN,9.0,2.0,1.0,NaN,NaN,26 m²,NaN,64976.0,https://realting.com/uploads/bigSlider/933/0fd...,https://realting.com/property-for-sale/russia/...
91318,"Cottage 202 m² in Barysaw, Belarus",Belarus,"Minsk Region, Barysaw, Barysaw District, Belarus",2007.0,NaN,NaN,NaN,NaN,NaN,202 m²,121 m²,698000.0,https://realting.com/uploads/bigSlider/78d/f5a...,https://realting.com/property-for-sale/belarus...
69105,3 room apartment 90 m² in Northern Administrat...,Russia,"Central Federal District, Northern Administrat...",NaN,NaN,NaN,3.0,NaN,NaN,90 m²,48 m²,626930.0,https://realting.com/uploads/bigSlider/e06/089...,https://realting.com/property-for-sale/russia/...

In [8]:
realestate_df.loc [3775] #testing

title                                        3 room apartment 160 m² in, Turkey
country                                                                  Turkey
location                                                                    NaN
building_construction_year                                                  NaN
building_total_floors                                                       3.0
apartment_floor                                                             NaN
apartment_rooms                                                             4.0
apartment_bedrooms                                                          3.0
apartment_bathrooms                                                         NaN
apartment_total_area                                                     160 m²
apartment_living_area                                                       NaN
price_in_USD                                                           647699.0
image                         https://realting.com/uploads/bigSlider/f05/5fa...
url                           https://realting.com/property-for-sale/turkey/...
Name: 3775, dtype: object

In [9]:
realestate_df.isnull().sum

<bound method DataFrame.sum of         title  country  location  building_construction_year  \
0       False    False     False                        True
1       False    False     False                       False
2       False    False     False                        True
3       False    False     False                       False
4       False    False     False                       False
...       ...      ...       ...                         ...
147531  False    False     False                        True
147532  False    False     False                       False
147533  False    False     False                        True
147534  False    False     False                       False
147535  False    False     False                        True

        building_total_floors  apartment_floor  apartment_rooms  \
0                       False            False            False
1                       False             True             True
2                       False            False            False
3                       False            False            False
4                       False            False            False
...                       ...              ...              ...
147531                   True             True             True
147532                  False             True            False
147533                   True             True            False
147534                   True             True             True
147535                  False             True            False

        apartment_bedrooms  apartment_bathrooms  apartment_total_area  \
0                    False                False                 False
1                     True                 True                 False
2                    False                False                 False
3                    False                False                  True
4                    False                False                  True
...                    ...                  ...                   ...
147531               False                 True                 False
147532               False                False                 False
147533               False                False                  True
147534                True                 True                  True
147535               False                 True                 False

        apartment_living_area  price_in_USD  image    url
0                       False         False  False  False
1                       False         False  False  False
2                       False         False  False  False
3                       False         False  False  False
4                       False         False  False  False
...                       ...           ...    ...    ...
147531                   True         False  False  False
147532                  False         False  False  False
147533                  False         False  False  False
147534                   True         False  False  False
147535                   True         False  False  False

[147536 rows x 14 columns]>

In [10]:
realestate_df

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
0,2 room apartment 120 m² in Mediterranean Regio...,Turkey,"Mediterranean Region, Turkey",NaN,5.0,1.0,3.0,2.0,2.0,120 m²,110 m²,315209.0,https://realting.com/uploads/bigSlider/ab3/888...,https://realting.com/property-for-sale/turkey/...
1,"4 room villa 500 m² in Kalkan, Turkey",Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,NaN,NaN,NaN,500 m²,480 m²,1108667.0,https://realting.com/uploads/bigSlider/87b/679...,https://realting.com/property-for-sale/turkey/...
2,"1 room apartment 65 m² in Antalya, Turkey",Turkey,"Mediterranean Region, Antalya, Turkey",NaN,5.0,2.0,2.0,1.0,1.0,65 m²,60 m²,173211.0,https://realting.com/uploads/bigSlider/030/a11...,https://realting.com/property-for-sale/turkey/...
3,"1 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2020.0,15.0,5.0,2.0,1.0,1.0,NaN,40 m²,99900.0,https://realting.com/uploads/bigSlider/e9a/e06...,https://realting.com/property-for-sale/thailan...
4,"2 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2026.0,8.0,3.0,3.0,2.0,1.0,NaN,36 m²,67000.0,https://realting.com/uploads/bigSlider/453/aa2...,https://realting.com/property-for-sale/thailan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147531,"5 room apartment 310 m² in Gazipasa, Turkey",Turkey,"Mediterranean Region, Gazipasa, Turkey",NaN,NaN,NaN,NaN,5.0,NaN,310 m²,NaN,597810.0,https://realting.com/uploads/bigSlider/e4a/67f...,https://realting.com/property-for-sale/turkey/...
147532,"4 room apartment 192 m² in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",2023.0,5.0,NaN,5.0,4.0,2.0,192 m²,151 m²,637195.0,https://realting.com/uploads/bigSlider/93e/5c6...,https://realting.com/property-for-sale/turkey/...
147533,"2 room apartment in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",NaN,NaN,NaN,3.0,2.0,2.0,NaN,84 m²,477146.0,https://realting.com/uploads/bigSlider/4ae/9d8...,https://realting.com/property-for-sale/turkey/...
147534,"Apartment in Akarca, Turkey",Turkey,"Akarca, Central Anatolia Region, Turkey",2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,819163.0,https://realting.com/uploads/bigSlider/164/7e6...,https://realting.com/property-for-sale/turkey/...
147535,"4 room apartment 140 m² in, Turkey",Turkey,Turkey,NaN,2.0,NaN,5.0,4.0,NaN,140 m²,NaN,939164.0,https://realting.com/uploads/bigSlider/fab/0eb...,https://realting.com/property-for-sale/turkey/...

In [11]:

def extract_best_location(row):
    url = row['url']
    title = row['title']
    country = row['country']

    # Taking the country from the URL 
    if pd.notna(url):
        parts = url.split('/')
        location_parts = [p.replace('-', ' ').title() for p in parts[5:-1] if p]
        if len(location_parts) >= 2:  #If the region is there to take it as well
            return ', '.join(location_parts)

    # If not in URL to check title 
    if pd.notna(title):
        match = re.search(r'in (.+)', title, re.IGNORECASE)
        if match:
            return match.group(1).strip()

    # If not in Title to check Country
    if pd.notna(country):
        return f"Unknown, {country}"

    return None

realestate_df

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
0,2 room apartment 120 m² in Mediterranean Regio...,Turkey,"Mediterranean Region, Turkey",NaN,5.0,1.0,3.0,2.0,2.0,120 m²,110 m²,315209.0,https://realting.com/uploads/bigSlider/ab3/888...,https://realting.com/property-for-sale/turkey/...
1,"4 room villa 500 m² in Kalkan, Turkey",Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,NaN,NaN,NaN,500 m²,480 m²,1108667.0,https://realting.com/uploads/bigSlider/87b/679...,https://realting.com/property-for-sale/turkey/...
2,"1 room apartment 65 m² in Antalya, Turkey",Turkey,"Mediterranean Region, Antalya, Turkey",NaN,5.0,2.0,2.0,1.0,1.0,65 m²,60 m²,173211.0,https://realting.com/uploads/bigSlider/030/a11...,https://realting.com/property-for-sale/turkey/...
3,"1 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2020.0,15.0,5.0,2.0,1.0,1.0,NaN,40 m²,99900.0,https://realting.com/uploads/bigSlider/e9a/e06...,https://realting.com/property-for-sale/thailan...
4,"2 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2026.0,8.0,3.0,3.0,2.0,1.0,NaN,36 m²,67000.0,https://realting.com/uploads/bigSlider/453/aa2...,https://realting.com/property-for-sale/thailan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147531,"5 room apartment 310 m² in Gazipasa, Turkey",Turkey,"Mediterranean Region, Gazipasa, Turkey",NaN,NaN,NaN,NaN,5.0,NaN,310 m²,NaN,597810.0,https://realting.com/uploads/bigSlider/e4a/67f...,https://realting.com/property-for-sale/turkey/...
147532,"4 room apartment 192 m² in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",2023.0,5.0,NaN,5.0,4.0,2.0,192 m²,151 m²,637195.0,https://realting.com/uploads/bigSlider/93e/5c6...,https://realting.com/property-for-sale/turkey/...
147533,"2 room apartment in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",NaN,NaN,NaN,3.0,2.0,2.0,NaN,84 m²,477146.0,https://realting.com/uploads/bigSlider/4ae/9d8...,https://realting.com/property-for-sale/turkey/...
147534,"Apartment in Akarca, Turkey",Turkey,"Akarca, Central Anatolia Region, Turkey",2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,819163.0,https://realting.com/uploads/bigSlider/164/7e6...,https://realting.com/property-for-sale/turkey/...
147535,"4 room apartment 140 m² in, Turkey",Turkey,Turkey,NaN,2.0,NaN,5.0,4.0,NaN,140 m²,NaN,939164.0,https://realting.com/uploads/bigSlider/fab/0eb...,https://realting.com/property-for-sale/turkey/...

In [12]:
realestate_df.loc [3775] #testing

title                                        3 room apartment 160 m² in, Turkey
country                                                                  Turkey
location                                                                    NaN
building_construction_year                                                  NaN
building_total_floors                                                       3.0
apartment_floor                                                             NaN
apartment_rooms                                                             4.0
apartment_bedrooms                                                          3.0
apartment_bathrooms                                                         NaN
apartment_total_area                                                     160 m²
apartment_living_area                                                       NaN
price_in_USD                                                           647699.0
image                         https://realting.com/uploads/bigSlider/f05/5fa...
url                           https://realting.com/property-for-sale/turkey/...
Name: 3775, dtype: object

In [13]:

import re  # <-- this is the missing import

def extract_best_location(row):
    url = row['url']
    title = row['title']
    country = row['country']

    # Try from URL
    if pd.notna(url):
        parts = url.split('/')
        location_parts = [p.replace('-', ' ').title() for p in parts[5:-1] if p]
        if len(location_parts) >= 2:
            return ', '.join(location_parts)

    # Try from Title
    if pd.notna(title):
        match = re.search(r'in (.+)', title, re.IGNORECASE)
        if match:
            return match.group(1).strip()

    # Fallback to Country
    if pd.notna(country):
        return f"Unknown, {country}"

    return None

# Apply to missing locations only
missing_location = realestate_df['location'].isna()
realestate_df.loc[missing_location, 'location'] = realestate_df[missing_location].apply(extract_best_location, axis=1)

In [14]:
realestate_df

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
0,2 room apartment 120 m² in Mediterranean Regio...,Turkey,"Mediterranean Region, Turkey",NaN,5.0,1.0,3.0,2.0,2.0,120 m²,110 m²,315209.0,https://realting.com/uploads/bigSlider/ab3/888...,https://realting.com/property-for-sale/turkey/...
1,"4 room villa 500 m² in Kalkan, Turkey",Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,NaN,NaN,NaN,500 m²,480 m²,1108667.0,https://realting.com/uploads/bigSlider/87b/679...,https://realting.com/property-for-sale/turkey/...
2,"1 room apartment 65 m² in Antalya, Turkey",Turkey,"Mediterranean Region, Antalya, Turkey",NaN,5.0,2.0,2.0,1.0,1.0,65 m²,60 m²,173211.0,https://realting.com/uploads/bigSlider/030/a11...,https://realting.com/property-for-sale/turkey/...
3,"1 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2020.0,15.0,5.0,2.0,1.0,1.0,NaN,40 m²,99900.0,https://realting.com/uploads/bigSlider/e9a/e06...,https://realting.com/property-for-sale/thailan...
4,"2 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2026.0,8.0,3.0,3.0,2.0,1.0,NaN,36 m²,67000.0,https://realting.com/uploads/bigSlider/453/aa2...,https://realting.com/property-for-sale/thailan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147531,"5 room apartment 310 m² in Gazipasa, Turkey",Turkey,"Mediterranean Region, Gazipasa, Turkey",NaN,NaN,NaN,NaN,5.0,NaN,310 m²,NaN,597810.0,https://realting.com/uploads/bigSlider/e4a/67f...,https://realting.com/property-for-sale/turkey/...
147532,"4 room apartment 192 m² in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",2023.0,5.0,NaN,5.0,4.0,2.0,192 m²,151 m²,637195.0,https://realting.com/uploads/bigSlider/93e/5c6...,https://realting.com/property-for-sale/turkey/...
147533,"2 room apartment in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",NaN,NaN,NaN,3.0,2.0,2.0,NaN,84 m²,477146.0,https://realting.com/uploads/bigSlider/4ae/9d8...,https://realting.com/property-for-sale/turkey/...
147534,"Apartment in Akarca, Turkey",Turkey,"Akarca, Central Anatolia Region, Turkey",2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,819163.0,https://realting.com/uploads/bigSlider/164/7e6...,https://realting.com/property-for-sale/turkey/...
147535,"4 room apartment 140 m² in, Turkey",Turkey,Turkey,NaN,2.0,NaN,5.0,4.0,NaN,140 m²,NaN,939164.0,https://realting.com/uploads/bigSlider/fab/0eb...,https://realting.com/property-for-sale/turkey/...

In [15]:
realestate_df.loc [29517] #testing

title                                        3 room apartment 106 m² in, Greece
country                                                                  Greece
location                                                        Unknown, Greece
building_construction_year                                               2023.0
building_total_floors                                                       1.0
apartment_floor                                                             3.0
apartment_rooms                                                             4.0
apartment_bedrooms                                                          3.0
apartment_bathrooms                                                         1.0
apartment_total_area                                                     106 m²
apartment_living_area                                                       NaN
price_in_USD                                                           429337.0
image                         https://realting.com/uploads/bigSlider/836/9d4...
url                           https://realting.com/property-for-sale/greece/...
Name: 29517, dtype: object

In [16]:
def fill_by_group_median(df, group_col, target_col):
    # Step 1: Fill missing with group medians only if group has valid values
    group_medians = df.groupby(group_col)[target_col].median()

    def safe_fill(row):
        if pd.isna(row[target_col]):
            median = group_medians.get(row[group_col])
            return median if pd.notna(median) else row[target_col]
        return row[target_col]

    return df.apply(safe_fill, axis=1)

In [17]:
# Bedrooms
realestate_df['apartment_bedrooms'] = fill_by_group_median(realestate_df, 'location', 'apartment_bedrooms')
realestate_df['apartment_bedrooms'].fillna(realestate_df['apartment_bedrooms'].median())

0         2.0
1         2.0
2         1.0
3         1.0
4         2.0
         ...
147531    5.0
147532    4.0
147533    2.0
147534    2.0
147535    4.0
Name: apartment_bedrooms, Length: 147536, dtype: float64

In [18]:
realestate_df['apartment_bathrooms'] = fill_by_group_median(realestate_df, 'location', 'apartment_bathrooms')
realestate_df['apartment_bathrooms'].fillna(realestate_df['apartment_bathrooms'].median())

0         2.0
1         1.0
2         1.0
3         1.0
4         1.0
         ...
147531    1.0
147532    2.0
147533    2.0
147534    2.0
147535    1.0
Name: apartment_bathrooms, Length: 147536, dtype: float64

In [19]:
realestate_df ['apartment_bathrooms'].isna().sum()

np.int64(24504)

In [20]:
realestate_df ['apartment_bedrooms'].isna().sum()

np.int64(47147)

In [21]:
def fill_year_by_group(df, group_cols, target_col):
    group_medians = df.groupby(group_cols)[target_col].median()

    def safe_fill(row):
        if pd.isna(row[target_col]):
            group_key = tuple(row[col] for col in group_cols) if isinstance(group_cols, list) else row[group_cols]
            median = group_medians.get(group_key)
            return median if pd.notna(median) else row[target_col]
        return row[target_col]

    return df.apply(safe_fill, axis=1)

In [22]:
realestate_df['building_construction_year'] = fill_year_by_group(
    realestate_df,
    group_cols=['location', 'building_total_floors'],
    target_col='building_construction_year'
)

In [23]:
median_year = realestate_df['building_construction_year'].median()
realestate_df['building_construction_year'].fillna(median_year)

0         2023.0
1         2021.0
2         2023.0
3         2020.0
4         2026.0
           ...
147531    2022.0
147532    2023.0
147533    2022.0
147534    2023.0
147535    2021.0
Name: building_construction_year, Length: 147536, dtype: float64

In [24]:
realestate_df.loc [21] #testing

title                                              Apartment  in Akarca, Turkey
country                                                                  Turkey
location                                Akarca, Central Anatolia Region, Turkey
building_construction_year                                               2022.0
building_total_floors                                                       NaN
apartment_floor                                                             NaN
apartment_rooms                                                             NaN
apartment_bedrooms                                                          2.0
apartment_bathrooms                                                         2.0
apartment_total_area                                                        NaN
apartment_living_area                                                       NaN
price_in_USD                                                           304177.0
image                         https://realting.com/uploads/bigSlider/909/2f9...
url                           https://realting.com/property-for-sale/turkey/...
Name: 21, dtype: object

In [25]:
realestate_df['building_construction_year'].isna().sum()

np.int64(67340)

In [26]:
mask1 = realestate_df['building_construction_year'].isna()
realestate_df.loc[mask1, 'building_construction_year'] = fill_year_by_group(
    realestate_df[mask1],
    group_cols='location',
    target_col='building_construction_year'
)

In [27]:
mask2 = realestate_df['building_construction_year'].isna()
realestate_df.loc[mask2, 'building_construction_year'] = fill_year_by_group(
    realestate_df[mask2],
    group_cols=['location', 'building_total_floors'],
    target_col='building_construction_year'
)

In [28]:
median_year = realestate_df['building_construction_year'].median()
realestate_df['building_construction_year'].fillna(median_year)

0         2023.0
1         2021.0
2         2023.0
3         2020.0
4         2026.0
           ...
147531    2022.0
147532    2023.0
147533    2022.0
147534    2023.0
147535    2021.0
Name: building_construction_year, Length: 147536, dtype: float64

In [29]:
realestate_df['building_construction_year'].isna().sum()

np.int64(67340)

In [30]:
realestate_df.loc [31] #testing

title                               2 room apartment 78 m² in Kotor, Montenegro
country                                                              Montenegro
location                                  Kotor, Kotor Municipality, Montenegro
building_construction_year                                                  NaN
building_total_floors                                                       NaN
apartment_floor                                                             NaN
apartment_rooms                                                             2.0
apartment_bedrooms                                                          2.0
apartment_bathrooms                                                         2.0
apartment_total_area                                                      78 m²
apartment_living_area                                                       NaN
price_in_USD                                                           263037.0
image                         https://realting.com/uploads/bigSlider/e7c/c99...
url                           https://realting.com/property-for-sale/montene...
Name: 31, dtype: object

In [32]:
from datetime import datetime
# Get the current year
current_year = datetime.now().year
# Make a copy of the original column to work on
realestate_df['construction_year_fixed'] = realestate_df['building_construction_year']
# Only update rows where the year is a number less than 1000 (assuming all real calendar years are >= 1000)
realestate_df.loc[
    (realestate_df['building_construction_year'] < 1000),
    'construction_year_fixed'
] = current_year - realestate_df['building_construction_year']
# Convert to integer (optional, handles NaNs safely)
realestate_df['construction_year_fixed'] = realestate_df['construction_year_fixed'].astype('Int64')
# Preview the result
realestate_df[['building_construction_year', 'construction_year_fixed']].head(10)

TypeError: cannot safely cast non-equivalent float64 to int64

In [33]:
from datetime import datetime
import numpy as np
# Get current year
current_year = datetime.now().year
# Make a copy of the column
realestate_df['construction_year_fixed'] = realestate_df['building_construction_year']
# Only convert values less than 1000 and not missing
realestate_df.loc[
    (realestate_df['building_construction_year'] < 1000) &
    (realestate_df['building_construction_year'].notna()),
    'construction_year_fixed'
] = current_year - realestate_df['building_construction_year']
# Convert to pandas nullable integer type (Int64) safely
realestate_df['construction_year_fixed'] = realestate_df['construction_year_fixed'].round().astype('Int64')
# Preview the results
realestate_df[['building_construction_year', 'construction_year_fixed']].head(10)

   building_construction_year  construction_year_fixed
0                      2023.0                     2023
1                      2021.0                     2021
2                      2023.0                     2023
3                      2020.0                     2020
4                      2026.0                     2026
5                      2026.0                     2026
6                      2007.0                     2007
7                      2026.0                     2026
8                         NaN                     <NA>
9                         NaN                     <NA>

In [34]:
mask1 = realestate_df['building_construction_year'].isna()
realestate_df.loc[mask1, 'building_construction_year'] = fill_year_by_group(
    realestate_df[mask1],
    group_cols='location',
    target_col='building_construction_year'
)

In [ ]:
mask2 = realestate_df['building_construction_year'].isna()
realestate_df.loc[mask2, 'building_construction_year'] = fill_year_by_group(
    realestate_df[mask2],
    group_cols=['location', 'building_total_floors'],
    target_col='building_construction_year'
)

In [35]:
median_year = realestate_df['building_construction_year'].median()
realestate_df['building_construction_year'].fillna(median_year)

0         2023.0
1         2021.0
2         2023.0
3         2020.0
4         2026.0
           ...
147531    2022.0
147532    2023.0
147533    2022.0
147534    2023.0
147535    2021.0
Name: building_construction_year, Length: 147536, dtype: float64

In [37]:
realestate_df['building_construction_year'].isna().sum()

np.int64(67340)

In [40]:
# Try location first
mask1 = realestate_df['building_construction_year'].isna()
realestate_df.loc[mask1, 'building_construction_year'] = fill_by_group_median(
    realestate_df[mask1],
    group_col='location',
    target_col='building_construction_year'
)

# Try (location + floors) next
mask2 = realestate_df['building_construction_year'].isna()
realestate_df.loc[mask2, 'building_construction_year'] = fill_by_group_median(
    realestate_df[mask2],
    group_col=['location', 'building_total_floors'],
    target_col='building_construction_year'
)

# Final fallback
median_year = realestate_df['building_construction_year'].median()
realestate_df['building_construction_year'].fillna(median_year)

0         2023.0
1         2021.0
2         2023.0
3         2020.0
4         2026.0
           ...
147531    2022.0
147532    2023.0
147533    2022.0
147534    2023.0
147535    2021.0
Name: building_construction_year, Length: 147536, dtype: float64

In [42]:
from datetime import datetime

current_year = datetime.now().year

# Copy the cleaned column
realestate_df['construction_year_fixed'] = realestate_df['building_construction_year']

# Convert values that look like age (< 1000)
realestate_df.loc[
    realestate_df['construction_year_fixed'] < 1000,
    'construction_year_fixed'
] = current_year - realestate_df['construction_year_fixed']

# Final type conversion
realestate_df['construction_year_fixed'] = realestate_df['construction_year_fixed'].round().astype('Int64')

In [43]:
realestate_df['building_construction_year'].isna().sum()

np.int64(0)

In [44]:
realestate_df.loc [31] #testing

title                               2 room apartment 78 m² in Kotor, Montenegro
country                                                              Montenegro
location                                  Kotor, Kotor Municipality, Montenegro
building_construction_year                                               2022.0
building_total_floors                                                       NaN
apartment_floor                                                             NaN
apartment_rooms                                                             2.0
apartment_bedrooms                                                          2.0
apartment_bathrooms                                                         2.0
apartment_total_area                                                      78 m²
apartment_living_area                                                       NaN
price_in_USD                                                           263037.0
image                         https://realting.com/uploads/bigSlider/e7c/c99...
url                           https://realting.com/property-for-sale/montene...
construction_year_fixed                                                    2022
Name: 31, dtype: object

In [47]:
realestate_df.drop(columns=['apartment_rooms', 'apartment_living_area', 'image'], inplace=True)

In [48]:
realestate_df

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_bedrooms,apartment_bathrooms,apartment_total_area,price_in_USD,url,construction_year_fixed
0,2 room apartment 120 m² in Mediterranean Regio...,Turkey,"Mediterranean Region, Turkey",2023.0,5.0,1.0,2.0,2.0,120 m²,315209.0,https://realting.com/property-for-sale/turkey/...,2023
1,"4 room villa 500 m² in Kalkan, Turkey",Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,2.0,1.0,500 m²,1108667.0,https://realting.com/property-for-sale/turkey/...,2021
2,"1 room apartment 65 m² in Antalya, Turkey",Turkey,"Mediterranean Region, Antalya, Turkey",2023.0,5.0,2.0,1.0,1.0,65 m²,173211.0,https://realting.com/property-for-sale/turkey/...,2023
3,"1 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2020.0,15.0,5.0,1.0,1.0,NaN,99900.0,https://realting.com/property-for-sale/thailan...,2020
4,"2 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2026.0,8.0,3.0,2.0,1.0,NaN,67000.0,https://realting.com/property-for-sale/thailan...,2026
...,...,...,...,...,...,...,...,...,...,...,...,...
147531,"5 room apartment 310 m² in Gazipasa, Turkey",Turkey,"Mediterranean Region, Gazipasa, Turkey",2022.0,NaN,NaN,5.0,1.0,310 m²,597810.0,https://realting.com/property-for-sale/turkey/...,2022
147532,"4 room apartment 192 m² in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",2023.0,5.0,NaN,4.0,2.0,192 m²,637195.0,https://realting.com/property-for-sale/turkey/...,2023
147533,"2 room apartment in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",2022.0,NaN,NaN,2.0,2.0,NaN,477146.0,https://realting.com/property-for-sale/turkey/...,2022
147534,"Apartment in Akarca, Turkey",Turkey,"Akarca, Central Anatolia Region, Turkey",2023.0,NaN,NaN,2.0,2.0,NaN,819163.0,https://realting.com/property-for-sale/turkey/...,2023
147535,"4 room apartment 140 m² in, Turkey",Turkey,Turkey,2021.0,2.0,NaN,4.0,1.0,140 m²,939164.0,https://realting.com/property-for-sale/turkey/...,2021