In [1]:
import pandas as pd

In [4]:
realestate_df = pd.read_csv('world_real_estate_data.csv')

In [5]:
realestate_df

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
0,2 room apartment 120 m² in Mediterranean Regio...,Turkey,"Mediterranean Region, Turkey",NaN,5.0,1.0,3.0,2.0,2.0,120 m²,110 m²,315209.0,https://realting.com/uploads/bigSlider/ab3/888...,https://realting.com/property-for-sale/turkey/...
1,"4 room villa 500 m² in Kalkan, Turkey",Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,NaN,NaN,NaN,500 m²,480 m²,1108667.0,https://realting.com/uploads/bigSlider/87b/679...,https://realting.com/property-for-sale/turkey/...
2,"1 room apartment 65 m² in Antalya, Turkey",Turkey,"Mediterranean Region, Antalya, Turkey",NaN,5.0,2.0,2.0,1.0,1.0,65 m²,60 m²,173211.0,https://realting.com/uploads/bigSlider/030/a11...,https://realting.com/property-for-sale/turkey/...
3,"1 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2020.0,15.0,5.0,2.0,1.0,1.0,NaN,40 m²,99900.0,https://realting.com/uploads/bigSlider/e9a/e06...,https://realting.com/property-for-sale/thailan...
4,"2 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2026.0,8.0,3.0,3.0,2.0,1.0,NaN,36 m²,67000.0,https://realting.com/uploads/bigSlider/453/aa2...,https://realting.com/property-for-sale/thailan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147531,"5 room apartment 310 m² in Gazipasa, Turkey",Turkey,"Mediterranean Region, Gazipasa, Turkey",NaN,NaN,NaN,NaN,5.0,NaN,310 m²,NaN,597810.0,https://realting.com/uploads/bigSlider/e4a/67f...,https://realting.com/property-for-sale/turkey/...
147532,"4 room apartment 192 m² in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",2023.0,5.0,NaN,5.0,4.0,2.0,192 m²,151 m²,637195.0,https://realting.com/uploads/bigSlider/93e/5c6...,https://realting.com/property-for-sale/turkey/...
147533,"2 room apartment in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",NaN,NaN,NaN,3.0,2.0,2.0,NaN,84 m²,477146.0,https://realting.com/uploads/bigSlider/4ae/9d8...,https://realting.com/property-for-sale/turkey/...
147534,"Apartment in Akarca, Turkey",Turkey,"Akarca, Central Anatolia Region, Turkey",2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,819163.0,https://realting.com/uploads/bigSlider/164/7e6...,https://realting.com/property-for-sale/turkey/...
147535,"4 room apartment 140 m² in, Turkey",Turkey,Turkey,NaN,2.0,NaN,5.0,4.0,NaN,140 m²,NaN,939164.0,https://realting.com/uploads/bigSlider/fab/0eb...,https://realting.com/property-for-sale/turkey/...

In [6]:
realestate_df.describe

<bound method NDFrame.describe of                                                     title   country  \
0       2 room apartment 120 m² in Mediterranean Regio...    Turkey
1                   4 room villa 500 m² in Kalkan, Turkey    Turkey
2               1 room apartment 65 m² in Antalya, Turkey    Turkey
3                  1 room apartment  in Pattaya, Thailand  Thailand
4                  2 room apartment  in Pattaya, Thailand  Thailand
...                                                   ...       ...
147531        5 room apartment 310 m² in Gazipasa, Turkey    Turkey
147532  4 room apartment 192 m² in Marmara Region, Turkey    Turkey
147533        2 room apartment  in Marmara Region, Turkey    Turkey
147534                       Apartment  in Akarca, Turkey    Turkey
147535                 4 room apartment 140 m² in, Turkey    Turkey

                                         location  building_construction_year  \
0                    Mediterranean Region, Turkey                         NaN
1       Kalkan, Mediterranean Region, Kas, Turkey                      2021.0
2           Mediterranean Region, Antalya, Turkey                         NaN
3           Chon Buri Province, Pattaya, Thailand                      2020.0
4           Chon Buri Province, Pattaya, Thailand                      2026.0
...                                           ...                         ...
147531     Mediterranean Region, Gazipasa, Turkey                         NaN
147532                     Marmara Region, Turkey                      2023.0
147533                     Marmara Region, Turkey                         NaN
147534    Akarca, Central Anatolia Region, Turkey                      2023.0
147535                                     Turkey                         NaN

        building_total_floors  apartment_floor  apartment_rooms  \
0                         5.0              1.0              3.0
1                         2.0              NaN              NaN
2                         5.0              2.0              2.0
3                        15.0              5.0              2.0
4                         8.0              3.0              3.0
...                       ...              ...              ...
147531                    NaN              NaN              NaN
147532                    5.0              NaN              5.0
147533                    NaN              NaN              3.0
147534                    NaN              NaN              NaN
147535                    2.0              NaN              5.0

        apartment_bedrooms  apartment_bathrooms apartment_total_area  \
0                      2.0                  2.0               120 m²
1                      NaN                  NaN               500 m²
2                      1.0                  1.0                65 m²
3                      1.0                  1.0                  NaN
4                      2.0                  1.0                  NaN
...                    ...                  ...                  ...
147531                 5.0                  NaN               310 m²
147532                 4.0                  2.0               192 m²
147533                 2.0                  2.0                  NaN
147534                 NaN                  NaN                  NaN
147535                 4.0                  NaN               140 m²

       apartment_living_area  price_in_USD  \
0                     110 m²      315209.0
1                     480 m²     1108667.0
2                      60 m²      173211.0
3                      40 m²       99900.0
4                      36 m²       67000.0
...                      ...           ...
147531                   NaN      597810.0
147532                151 m²      637195.0
147533                 84 m²      477146.0
147534                   NaN      819163.0
147535                   NaN      939164.0

                                                    image  \
0       https://realting.com/uploads/bigSlider/ab3/888...
1       https://realting.com/uploads/bigSlider/87b/679...
2       https://realting.com/uploads/bigSlider/030/a11...
3       https://realting.com/uploads/bigSlider/e9a/e06...
4       https://realting.com/uploads/bigSlider/453/aa2...
...                                                   ...
147531  https://realting.com/uploads/bigSlider/e4a/67f...
147532  https://realting.com/uploads/bigSlider/93e/5c6...
147533  https://realting.com/uploads/bigSlider/4ae/9d8...
147534  https://realting.com/uploads/bigSlider/164/7e6...
147535  https://realting.com/uploads/bigSlider/fab/0eb...

                                                      url
0       https://realting.com/property-for-sale/turkey/...
1       https://realting.com/property-for-sale/turkey/...
2       https://realting.com/property-for-sale/turkey/...
3       https://realting.com/property-for-sale/thailan...
4       https://realting.com/property-for-sale/thailan...
...                                                   ...
147531  https://realting.com/property-for-sale/turkey/...
147532  https://realting.com/property-for-sale/turkey/...
147533  https://realting.com/property-for-sale/turkey/...
147534  https://realting.com/property-for-sale/turkey/...
147535  https://realting.com/property-for-sale/turkey/...

[147536 rows x 14 columns]>

In [8]:
realestate_df.sample(5)

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
115155,"5 room apartment 128 m² in Zagreb, Croatia",Croatia,"Zagreb, Croatia",NaN,NaN,NaN,5.0,NaN,2.0,128 m²,NaN,1109886.0,https://realting.com/uploads/bigSlider/b5a/461...,https://realting.com/property-for-sale/croatia...
133491,"Condo 2 bedrooms 70 m² in Phuket, Thailand",Thailand,"Phuket Province, Phuket, Thailand",NaN,NaN,NaN,NaN,2.0,NaN,70 m²,NaN,219586.0,https://realting.com/uploads/bigSlider/8eb/c68...,https://realting.com/property-for-sale/thailan...
125313,"3 room house in Municipality of Thassos, Greece",Greece,"Macedonia and Thrace, Municipality of Thassos,...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,164 m²,140734.0,https://realting.com/uploads/bigSlider/599/350...,https://realting.com/property-for-sale/greece/...
126124,"Townhouse 2 bedrooms 85 m² in Nikiti, Greece",Greece,"Nikiti, Macedonia and Thrace, The Municipality...",2021.0,1.0,NaN,NaN,NaN,NaN,85 m²,NaN,174873.0,https://realting.com/uploads/bigSlider/d4a/664...,https://realting.com/property-for-sale/greece/...
44526,"5 room house 150 m² in Nagykovacsi, Hungary",Hungary,"Nagykovacsi, Central Hungary, Budakeszi jaras,...",NaN,NaN,NaN,NaN,NaN,NaN,150 m²,NaN,242105.0,https://realting.com/uploads/bigSlider/db1/870...,https://realting.com/property-for-sale/hungary...

In [9]:
realestate_df.head()

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
0,2 room apartment 120 m² in Mediterranean Regio...,Turkey,"Mediterranean Region, Turkey",NaN,5.0,1.0,3.0,2.0,2.0,120 m²,110 m²,315209.0,https://realting.com/uploads/bigSlider/ab3/888...,https://realting.com/property-for-sale/turkey/...
1,"4 room villa 500 m² in Kalkan, Turkey",Turkey,"Kalkan, Mediterranean Region, Kas, Turkey",2021.0,2.0,NaN,NaN,NaN,NaN,500 m²,480 m²,1108667.0,https://realting.com/uploads/bigSlider/87b/679...,https://realting.com/property-for-sale/turkey/...
2,"1 room apartment 65 m² in Antalya, Turkey",Turkey,"Mediterranean Region, Antalya, Turkey",NaN,5.0,2.0,2.0,1.0,1.0,65 m²,60 m²,173211.0,https://realting.com/uploads/bigSlider/030/a11...,https://realting.com/property-for-sale/turkey/...
3,"1 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2020.0,15.0,5.0,2.0,1.0,1.0,NaN,40 m²,99900.0,https://realting.com/uploads/bigSlider/e9a/e06...,https://realting.com/property-for-sale/thailan...
4,"2 room apartment in Pattaya, Thailand",Thailand,"Chon Buri Province, Pattaya, Thailand",2026.0,8.0,3.0,3.0,2.0,1.0,NaN,36 m²,67000.0,https://realting.com/uploads/bigSlider/453/aa2...,https://realting.com/property-for-sale/thailan...

In [10]:
realestate_df.tail()

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
147531,"5 room apartment 310 m² in Gazipasa, Turkey",Turkey,"Mediterranean Region, Gazipasa, Turkey",NaN,NaN,NaN,NaN,5.0,NaN,310 m²,NaN,597810.0,https://realting.com/uploads/bigSlider/e4a/67f...,https://realting.com/property-for-sale/turkey/...
147532,"4 room apartment 192 m² in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",2023.0,5.0,NaN,5.0,4.0,2.0,192 m²,151 m²,637195.0,https://realting.com/uploads/bigSlider/93e/5c6...,https://realting.com/property-for-sale/turkey/...
147533,"2 room apartment in Marmara Region, Turkey",Turkey,"Marmara Region, Turkey",NaN,NaN,NaN,3.0,2.0,2.0,NaN,84 m²,477146.0,https://realting.com/uploads/bigSlider/4ae/9d8...,https://realting.com/property-for-sale/turkey/...
147534,"Apartment in Akarca, Turkey",Turkey,"Akarca, Central Anatolia Region, Turkey",2023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,819163.0,https://realting.com/uploads/bigSlider/164/7e6...,https://realting.com/property-for-sale/turkey/...
147535,"4 room apartment 140 m² in, Turkey",Turkey,Turkey,NaN,2.0,NaN,5.0,4.0,NaN,140 m²,NaN,939164.0,https://realting.com/uploads/bigSlider/fab/0eb...,https://realting.com/property-for-sale/turkey/...

In [14]:
realestate_df.shape

(147536, 14)

In [15]:
realestate_df.dtypes

title                          object
country                        object
location                       object
building_construction_year    float64
building_total_floors         float64
apartment_floor               float64
apartment_rooms               float64
apartment_bedrooms            float64
apartment_bathrooms           float64
apartment_total_area           object
apartment_living_area          object
price_in_USD                  float64
image                          object
url                            object
dtype: object

In [16]:
realestate_df.size

2065504

In [17]:
realestate_df.info

<bound method DataFrame.info of                                                     title   country  \
0       2 room apartment 120 m² in Mediterranean Regio...    Turkey
1                   4 room villa 500 m² in Kalkan, Turkey    Turkey
2               1 room apartment 65 m² in Antalya, Turkey    Turkey
3                  1 room apartment  in Pattaya, Thailand  Thailand
4                  2 room apartment  in Pattaya, Thailand  Thailand
...                                                   ...       ...
147531        5 room apartment 310 m² in Gazipasa, Turkey    Turkey
147532  4 room apartment 192 m² in Marmara Region, Turkey    Turkey
147533        2 room apartment  in Marmara Region, Turkey    Turkey
147534                       Apartment  in Akarca, Turkey    Turkey
147535                 4 room apartment 140 m² in, Turkey    Turkey

                                         location  building_construction_year  \
0                    Mediterranean Region, Turkey                         NaN
1       Kalkan, Mediterranean Region, Kas, Turkey                      2021.0
2           Mediterranean Region, Antalya, Turkey                         NaN
3           Chon Buri Province, Pattaya, Thailand                      2020.0
4           Chon Buri Province, Pattaya, Thailand                      2026.0
...                                           ...                         ...
147531     Mediterranean Region, Gazipasa, Turkey                         NaN
147532                     Marmara Region, Turkey                      2023.0
147533                     Marmara Region, Turkey                         NaN
147534    Akarca, Central Anatolia Region, Turkey                      2023.0
147535                                     Turkey                         NaN

        building_total_floors  apartment_floor  apartment_rooms  \
0                         5.0              1.0              3.0
1                         2.0              NaN              NaN
2                         5.0              2.0              2.0
3                        15.0              5.0              2.0
4                         8.0              3.0              3.0
...                       ...              ...              ...
147531                    NaN              NaN              NaN
147532                    5.0              NaN              5.0
147533                    NaN              NaN              3.0
147534                    NaN              NaN              NaN
147535                    2.0              NaN              5.0

        apartment_bedrooms  apartment_bathrooms apartment_total_area  \
0                      2.0                  2.0               120 m²
1                      NaN                  NaN               500 m²
2                      1.0                  1.0                65 m²
3                      1.0                  1.0                  NaN
4                      2.0                  1.0                  NaN
...                    ...                  ...                  ...
147531                 5.0                  NaN               310 m²
147532                 4.0                  2.0               192 m²
147533                 2.0                  2.0                  NaN
147534                 NaN                  NaN                  NaN
147535                 4.0                  NaN               140 m²

       apartment_living_area  price_in_USD  \
0                     110 m²      315209.0
1                     480 m²     1108667.0
2                      60 m²      173211.0
3                      40 m²       99900.0
4                      36 m²       67000.0
...                      ...           ...
147531                   NaN      597810.0
147532                151 m²      637195.0
147533                 84 m²      477146.0
147534                   NaN      819163.0
147535                   NaN      939164.0

                                                    image  \
0       https://realting.com/uploads/bigSlider/ab3/888...
1       https://realting.com/uploads/bigSlider/87b/679...
2       https://realting.com/uploads/bigSlider/030/a11...
3       https://realting.com/uploads/bigSlider/e9a/e06...
4       https://realting.com/uploads/bigSlider/453/aa2...
...                                                   ...
147531  https://realting.com/uploads/bigSlider/e4a/67f...
147532  https://realting.com/uploads/bigSlider/93e/5c6...
147533  https://realting.com/uploads/bigSlider/4ae/9d8...
147534  https://realting.com/uploads/bigSlider/164/7e6...
147535  https://realting.com/uploads/bigSlider/fab/0eb...

                                                      url
0       https://realting.com/property-for-sale/turkey/...
1       https://realting.com/property-for-sale/turkey/...
2       https://realting.com/property-for-sale/turkey/...
3       https://realting.com/property-for-sale/thailan...
4       https://realting.com/property-for-sale/thailan...
...                                                   ...
147531  https://realting.com/property-for-sale/turkey/...
147532  https://realting.com/property-for-sale/turkey/...
147533  https://realting.com/property-for-sale/turkey/...
147534  https://realting.com/property-for-sale/turkey/...
147535  https://realting.com/property-for-sale/turkey/...

[147536 rows x 14 columns]>

In [18]:
realestate_df.columns

Index(['title', 'country', 'location', 'building_construction_year',
       'building_total_floors', 'apartment_floor', 'apartment_rooms',
       'apartment_bedrooms', 'apartment_bathrooms', 'apartment_total_area',
       'apartment_living_area', 'price_in_USD', 'image', 'url'],
      dtype='object')

In [19]:
realestate_df.isnull()

,title,country,location,building_construction_year,building_total_floors,apartment_floor,apartment_rooms,apartment_bedrooms,apartment_bathrooms,apartment_total_area,apartment_living_area,price_in_USD,image,url
0,False,False,False,True,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,True,True,True,False,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147531,False,False,False,True,True,True,True,False,True,False,True,False,False,False
147532,False,False,False,False,False,True,False,False,False,False,False,False,False,False
147533,False,False,False,True,True,True,False,False,False,True,False,False,False,False
147534,False,False,False,False,True,True,True,True,True,True,True,False,False,False
147535,False,False,False,True,False,True,False,False,True,False,True,False,False,False

In [20]:
realestate_df.isnull().sum()

title                              0
country                          130
location                         131
building_construction_year     82817
building_total_floors          79312
apartment_floor                92944
apartment_rooms                73358
apartment_bedrooms            110554
apartment_bathrooms            91563
apartment_total_area            5740
apartment_living_area         119824
price_in_USD                    2575
image                              0
url                                0
dtype: int64

In [21]:
realestate_df.isnull().sum().sum()

658948